// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/validate-seo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.24.2";

// src/lib/mcp/lib/fetchPage.ts
var SITE = "https://tecnico.curitiba.br";
function normalizePath(input) {
  const raw = (input || "/").trim();
  const path = raw.startsWith("http") ? new URL(raw).pathname : raw;
  return path.startsWith("/") ? path.replace(/\s/g, "") : `/${path}`;
}
async function fetchPublicPage(path) {
  const url = `${SITE}${normalizePath(path)}`;
  const res = await fetch(url, {
    redirect: "follow",
    headers: { "user-agent": "tecnico-curitiba-mcp/1.0 (+seo-validation)" }
  });
  const html = res.ok ? await res.text() : "";
  return { url, status: res.status, ok: res.ok, html, finalUrl: res.url };
}
function extractJsonLd(html) {
  const blocos = [];
  const re = /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let m;
  while (m = re.exec(html)) {
    try {
      const parsed = JSON.parse(m[1].trim());
      const nodes = [];
      const flatten = (n) => {
        if (Array.isArray(n)) n.forEach(flatten);
        else if (n && typeof n === "object") {
          nodes.push(n);
          const graph = n["@graph"];
          if (Array.isArray(graph)) graph.forEach(flatten);
        }
      };
      flatten(parsed);
      const tipos = nodes.map((n) => n["@type"]).flatMap((t) => Array.isArray(t) ? t : [t]).filter((t) => typeof t === "string");
      blocos.push({ valido: true, tipos });
    } catch (e) {
      blocos.push({ valido: false, tipos: [], erro: String(e) });
    }
  }
  return blocos;
}
var meta = (html, prop) => html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${prop}["'][^>]+content=["']([^"']*)["']`, "i"))?.[1];
var textOf = (html, tag) => html.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)</${tag}>`, "i"))?.[1]?.replace(/<[^>]+>/g, "").trim();

// src/lib/mcp/tools/validate-seo.ts
var validate_seo_default = defineTool({
  name: "validate_seo",
  title: "Validar SEO t\xE9cnico de uma rota",
  description: "Verifica, no HTML p\xFAblico de uma rota do site, o status HTTP, title, meta description, robots, canonical \xFAnico e self-referente, og:url e presen\xE7a de H1 \xFAnico.",
  inputSchema: {
    path: z.string().describe("Caminho p\xFAblico da rota, ex.: /servicos/conserto-monitor")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ path }) => {
    const rota = normalizePath(path);
    const page = await fetchPublicPage(rota);
    if (!page.ok) {
      return {
        content: [{ type: "text", text: `HTTP ${page.status} em ${page.url}` }],
        structuredContent: { url: page.url, status: page.status, problemas: [`HTTP ${page.status}`] },
        isError: true
      };
    }
    const html = page.html;
    const esperado = `${SITE}${rota}`;
    const canonicals = html.match(/<link[^>]+rel=["']canonical["'][^>]*>/gi) ?? [];
    const canonical = canonicals[0]?.match(/href=["']([^"']+)["']/i)?.[1];
    const h1s = html.match(/<h1[\s>]/gi) ?? [];
    const title = textOf(html, "title") ?? "";
    const description = meta(html, "description") ?? "";
    const robots = meta(html, "robots") ?? "index, follow";
    const ogUrl = meta(html, "og:url");
    const norm = (u) => (u || "").replace(/\/$/, "") || "/";
    const problemas = [];
    if (!title) problemas.push("title ausente");
    else if (title.length > 65) problemas.push(`title com ${title.length} caracteres (>65)`);
    if (!description) problemas.push("meta description ausente");
    else if (description.length > 250) problemas.push(`description com ${description.length} caracteres (>250)`);
    if (canonicals.length !== 1) problemas.push(`${canonicals.length} tags canonical (esperado 1)`);
    else if (norm(canonical) !== norm(esperado)) problemas.push(`canonical n\xE3o self-referente: ${canonical}`);
    if (!ogUrl) problemas.push("og:url ausente");
    else if (norm(ogUrl) !== norm(esperado)) problemas.push(`og:url n\xE3o self-referente: ${ogUrl}`);
    if (h1s.length !== 1) problemas.push(`${h1s.length} H1 na p\xE1gina (esperado 1)`);
    const resumo = {
      url: page.url,
      status: page.status,
      title,
      description,
      robots,
      canonical,
      ogUrl,
      h1Count: h1s.length,
      problemas,
      aprovado: problemas.length === 0
    };
    return {
      content: [
        {
          type: "text",
          text: problemas.length ? `${rota}: ${problemas.length} problema(s)
- ${problemas.join("\n- ")}` : `${rota}: SEO t\xE9cnico aprovado (title, description, canonical, og:url e H1 corretos).`
        }
      ],
      structuredContent: resumo
    };
  }
});

// src/lib/mcp/tools/validate-jsonld.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.24.2";
var validate_jsonld_default = defineTool2({
  name: "validate_jsonld",
  title: "Validar JSON-LD de uma rota",
  description: "Extrai todos os blocos JSON-LD do HTML p\xFAblico de uma rota, reporta erros de parse, lista os @type encontrados e alerta sobre rating/review inventados ou blocos duplicados.",
  inputSchema: {
    path: z2.string().describe("Caminho p\xFAblico da rota, ex.: /problemas/computador-nao-liga"),
    tiposEsperados: z2.array(z2.string()).optional().describe("Tipos schema.org que devem existir, ex.: ['FAQPage','Service']")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ path, tiposEsperados }) => {
    const rota = normalizePath(path);
    const page = await fetchPublicPage(rota);
    if (!page.ok) {
      return { content: [{ type: "text", text: `HTTP ${page.status} em ${page.url}` }], isError: true };
    }
    const blocos = extractJsonLd(page.html);
    const tipos = [...new Set(blocos.flatMap((b) => b.tipos))];
    const problemas = [];
    if (blocos.length === 0) problemas.push("nenhum bloco JSON-LD encontrado");
    blocos.forEach((b, i) => {
      if (!b.valido) problemas.push(`bloco ${i + 1} inv\xE1lido: ${b.erro}`);
    });
    for (const esperado of tiposEsperados ?? []) {
      if (!tipos.includes(esperado)) problemas.push(`@type esperado ausente: ${esperado}`);
    }
    const duplicados = tipos.filter(
      (t) => ["FAQPage", "BreadcrumbList", "Organization", "LocalBusiness"].includes(t) && blocos.flatMap((b) => b.tipos).filter((x) => x === t).length > 1
    );
    for (const d of new Set(duplicados)) problemas.push(`@type duplicado no documento: ${d}`);
    if (/"aggregateRating"|"reviewRating"/.test(page.html)) {
      problemas.push("rating/review presente \u2014 s\xF3 \xE9 permitido com avalia\xE7\xF5es reais verificadas");
    }
    return {
      content: [
        {
          type: "text",
          text: `${rota}: ${blocos.length} bloco(s) JSON-LD \u2014 tipos: ${tipos.join(", ") || "nenhum"}` + (problemas.length ? `
Problemas:
- ${problemas.join("\n- ")}` : "\nSem problemas.")
        }
      ],
      structuredContent: { url: page.url, blocos: blocos.length, tipos, problemas, aprovado: problemas.length === 0 }
    };
  }
});

// src/lib/mcp/tools/check-geo-conformance.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.24.2";
var check_geo_conformance_default = defineTool3({
  name: "check_geo_conformance",
  title: "Checar conformidade GEO de rotas",
  description: "Audita rotas p\xFAblicas quanto \xE0 conformidade GEO: H1 \xFAnico, title/description dentro dos limites, canonical e og:url self-referentes, robots index\xE1vel, JSON-LD v\xE1lido e corpo de texto suficiente j\xE1 no HTML pr\xE9-hidrata\xE7\xE3o.",
  inputSchema: {
    paths: z3.array(z3.string()).describe("Rotas p\xFAblicas a auditar, ex.: ['/', '/servicos']"),
    minPalavras: z3.number().optional().describe("M\xEDnimo de palavras no HTML est\xE1tico (padr\xE3o 300)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ paths, minPalavras }) => {
    const minimo = minPalavras && minPalavras > 0 ? Math.min(minPalavras, 2e3) : 300;
    const alvos = paths.slice(0, 25).map(normalizePath);
    const linhas = [];
    const resultados = [];
    for (const rota of alvos) {
      const page = await fetchPublicPage(rota);
      const problemas = [];
      if (!page.ok) {
        problemas.push(`HTTP ${page.status}`);
        resultados.push({ rota, aprovado: false, problemas });
        linhas.push(`\u2716 ${rota} \u2014 HTTP ${page.status}`);
        continue;
      }
      const html = page.html;
      const esperado = `${SITE}${rota}`;
      const norm = (u) => (u || "").replace(/\/$/, "") || "/";
      const canonical = html.match(/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i)?.[1];
      const h1s = (html.match(/<h1[\s>]/gi) ?? []).length;
      const title = textOf(html, "title") ?? "";
      const description = meta(html, "description") ?? "";
      const robots = (meta(html, "robots") ?? "index, follow").toLowerCase();
      const ogUrl = meta(html, "og:url");
      const corpo = html.replace(/<script[\s\S]*?<\/script>/gi, " ").replace(/<style[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ");
      const palavras = corpo.split(/\s+/).filter((w) => w.length > 1).length;
      const jsonld = extractJsonLd(html);
      if (h1s !== 1) problemas.push(`${h1s} H1 (esperado 1)`);
      if (!title) problemas.push("title ausente");
      else if (title.length > 65) problemas.push(`title ${title.length} chars`);
      if (!description) problemas.push("description ausente");
      else if (description.length > 250) problemas.push(`description ${description.length} chars`);
      if (norm(canonical) !== norm(esperado)) problemas.push(`canonical n\xE3o self (${canonical ?? "ausente"})`);
      if (norm(ogUrl) !== norm(esperado)) problemas.push(`og:url n\xE3o self (${ogUrl ?? "ausente"})`);
      if (robots.includes("noindex")) problemas.push("robots noindex");
      if (jsonld.length === 0) problemas.push("sem JSON-LD");
      if (jsonld.some((b) => !b.valido)) problemas.push("JSON-LD inv\xE1lido");
      if (palavras < minimo) problemas.push(`${palavras} palavras no HTML est\xE1tico (< ${minimo})`);
      resultados.push({ rota, palavras, h1s, canonical, ogUrl, robots, aprovado: problemas.length === 0, problemas });
      linhas.push(problemas.length ? `\u2716 ${rota} \u2014 ${problemas.join("; ")}` : `\u2713 ${rota} \u2014 conforme (${palavras} palavras)`);
    }
    const reprovadas = resultados.filter((r) => !r.aprovado).length;
    return {
      content: [{ type: "text", text: `${alvos.length} rota(s) auditada(s), ${reprovadas} reprovada(s):
${linhas.join("\n")}` }],
      structuredContent: { total: alvos.length, reprovadas, resultados }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "tecnico-curitiba-br",
  title: "Tecnico.Curitiba.br",
  version: "0.1.0",
  instructions: "Ferramentas de valida\xE7\xE3o t\xE9cnica de SEO do site T\xE9cnico em Curitiba. Use `validate_seo` para conferir title, description, canonical, og:url e H1 de uma rota p\xFAblica; `validate_jsonld` para extrair e validar os blocos schema.org; e `check_geo_conformance` para auditar em lote a conformidade GEO (conte\xFAdo leg\xEDvel sem JavaScript) de v\xE1rias rotas. Todas leem apenas HTML p\xFAblico do site.",
  tools: [validate_seo_default, validate_jsonld_default, check_geo_conformance_default],
  // Exige OAuth: só tokens válidos emitidos pelo backend do projeto podem
  // chamar as ferramentas. Sem isso o servidor MCP fica público após publicar.
  auth: auth.oauth.issuer({
    issuer: `${SUPABASE_URL}/auth/v1`,
    jwksUri: `${SUPABASE_URL}/auth/v1/.well-known/jwks.json`,
    acceptedAudiences: ["authenticated"],
    resource: `${SUPABASE_URL}/functions/v1/mcp`,
    resourceName: "Tecnico.Curitiba.br MCP"
  })
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
